### ISSUE TITLE
Padding page shows content very slowly.

### ISSUE THREAD

**Issue by paiext** [pureqml/pureqml-web#13]
pls check out the below link
https://pureqml.com/docs/controls.core/Paddings.html

**Comment by comrat** [comment]
@paiext 
I don't see any problems yet.
Can you try to reproduce this issue again?

**Comment by whoozle** [comment]
could be text alignment issue fixed in qmlcore some time ago (+1/-1px tolerance)

**Comment by whoozle** [comment]
fixed in qmlcore:a1df3a14a270e3c90e48fb43be5c8e880e78917b
