### ISSUE TITLE
Layout example code does not display normally.

### ISSUE THREAD

**Issue by paiext** [pureqml/pureqml-web#14]
The example on the page below does not display normally at first.
In the laptop, when I change the size of the window, the example is displayed normally.
On my desktop, it will appear normal after approximately 5 seconds.

https://pureqml.com/lessons/layouts.html

![image](https://user-images.githubusercontent.com/5268554/74850528-71979b80-537d-11ea-90aa-1712714cbfa0.png)

**Comment by comrat** [comment]
@paiext 
it looks like it's fixed now
