### ISSUE TITLE
The examples of 'Inputs' page are not immediately displayed.

### ISSUE THREAD

**Issue by paiext** [pureqml/pureqml-web#15]
The below page is initially displayed with no code visible as shown below.
https://pureqml.com/lessons/inputs.html

![image](https://user-images.githubusercontent.com/5268554/75010511-aeb87680-54c0-11ea-84f0-26e383d08e6f.png)

It is normally displayed after about 5 seconds or  when the window is resized.

**Comment by comrat** [comment]
This is the [same issue](https://github.com/pureqml/pureqml-web/issues/14)
