### ISSUE TITLE
History API fallback

### ISSUE THREAD

**Issue by azchatlanin** [pureqml/pureqml-web#3]
Hello friends. Constantly monitor your work in this direction. And you fellows.

On site of your (http://pureqml.com/)  when you go back from one page to another, the site thinks for a long time what to do. And while he thinks I can scroll a few pages back.

**Comment by comrat** [comment]
Hello @Luummii!
Can you please provide step-by-step reproducing the case how you did the site 'thinks for a long time'

**Comment by Luummii** [comment]
11.11.2017, 12:56, "Alexey" <notifications@github.com>:Hello @Luummii!
Can you please provide step-by-step reproducing the case how you did the site 'thinks for a long time'

**Comment by azchatlanin** [comment]
Send you mail - team@pureqml.com

**Comment by comrat** [comment]
Fixed and deployed
