### ISSUE TITLE
Search don`t work

### ISSUE THREAD

**Issue by azchatlanin** [pureqml/pureqml-web#6]
Search don`t work on the site.

**Comment by comrat** [comment]
@Luummii can you provide any information how to reproduce this bug?
I've tried to type 'Item' and it works correctly
![screenshot from 2018-11-20 01-11-24](https://user-images.githubusercontent.com/4650233/48738221-53665b80-ec61-11e8-862f-7ebe81d935df.png)

**Comment by azchatlanin** [comment]
I checked the text search on the main. For example: PureQML, declarative, front, framework...
Ctrl-C and Ctrl-V.

**Comment by comrat** [comment]
Search works only for documentation right now.
We've put 'Documentation search' placeholder there to avoid any confusion
